[project]
name = "callgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "assemblyai==0.44.3",
    "fastapi[standard]>=0.121.1",
    "flake8>=7.3.0",
    "langchain>=0.1.0",
    "langchain-community>=0.4.1",
    "langchain-groq>=1.0.0",
    "langchain-huggingface>=1.0.1",
    "langchain-text-splitters>=1.0.0",
    "langgraph>=1.0.3",
    "langgraph-checkpoint-sqlite>=3.0.0",
    "make>=0.1.6.post2",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "python-dotenv==1.0.0",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.1.2",
    "streamlit>=1.51.0",
    "supabase>=2.24.0",
    "tqdm>=4.67.1",
    "uvicorn[standard]>=0.38.0",
    "vapi-server-sdk>=1.7.3",
]

[tool.uv.workspace]
members = [
    "services/document_service",
    "services/embedding_service",
    "services/llm_service",
    "services/api_gateway",
    "services/retrieval_service",
    "services/conversation_service",
    "services/vectorstore_service",
]
